# Generated by Django 5.1.7 on 2025-03-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('driving_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rest_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('location', models.CharField(max_length=255)),
                ('log_generated', models.BooleanField(default=False)),
            ],
        ),
    ]
